# rubocop:disable Naming/FileName, Metrics/BlockLength, Lint/MissingCopEnableDirective
# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Get latest dsysms and upload to bugsnag'
  lane :refresh_dsyms do
    download_dsyms(
      version: 'latest',
      api_key_path: './fastlane/api_key.json',
      wait_for_dsym_processing: true
    )
    upload_symbols_to_bugsnag
  end

  desc 'Push a new build to TestFlight'
  lane :release do
    increment_build_number(xcodeproj: 'Golfer.xcodeproj')
    build_app(
      workspace: 'Golfer.xcworkspace',
      scheme: 'Golfer',
      include_symbols: true,
      include_bitcode: true
    )
    changelog_from_git_commits
    upload_to_testflight(
      api_key_path: './fastlane/api_key.json',
      demo_account_required: false,
      notify_external_testers: true,
      distribute_external: true,
      groups: ['External'],
    )
    refresh_dsyms
    add_git_tag(
      grouping: 'release',
      includes_lane: false,
      prefix: 'v'
    )
    clean_build_artifacts
  end
end
